 
 
CREATE   VIEW [ml_mart].[fact_MathReportByPlayersRich]
AS
SELECT 
	main.[MatchDateID]
	,cal.[DateTime]
	,main.[SeasonID]
	,main.[FolderName]
	,main.[StageID]
	,main.[HostCityID]
	,main.[HostTeamID]
	,main.[GuestTeamID]
	,main.[OpponentTeamName]
	,main.[TeamID]
	,main.[PlayerTeamName]
	,main.[PlayerID]
	,play.[PlayerHeight]
	,main.[PlayerName]
	,main.[PlayerNumber]
	,main.[Set1]
	,main.[Set2]
	,main.[Set3]
	,main.[Set4]
	,main.[Set5]
	,main.[TotalPoints]
	,main.[BreakPoints]
	,main.[ScoredLostPoints]
	,main.[TotalServes]
	,main.[ServeErrors]
	,main.[ServePoints]
	,main.[TotalReceptions]
	,main.[ReceptionErrors]
	,main.[PerfectReceptionPercent]
	,main.[ExcellentReceptionPercent]
	,main.[TotalAttacks]
	,main.[AttackErrors]
	,main.[AttackBlocks]
	,main.[AttackPoints]
	,main.[AttackPointPercent]
	,main.[BlockPoints]
FROM [Volleyball_dwh].[dbo].[fact_MatchStatsPlayers] AS main
LEFT JOIN [dim_Date] AS cal
	ON cal.[DateID] = main.[MatchDateID]
LEFT JOIN [dbo].[dim_Players] AS play
	ON play.[PlayerID] = main.[PlayerID]